services:
  # 1. กล่องฐานข้อมูล PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: lab_postgres
    restart: always
    environment:
      # ดึงรหัสผ่านและค่าต่างๆ มาจากไฟล์ .env
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. กล่อง Cache Redis
  redis-cache:
    image: redis:7-alpine
    container_name: lab_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  pgdata:
